#!/bin/sh

cd /var/www

# コンテナ起動時には環境変数が解決されているためここでキャッシュする
php artisan config:cache
# イメージビルド時には環境変数が解決されていないので
# config 以外も正しいキャッシュが生成されないのでここでキャッシュする
php artisan route:cache
php artisan view:cache

# コンテナ起動時にMigrateしておく
# 一般的にはバッドプラクティスだが、
# 実行環境は確実にDBと接続できる状態であるため、
# マイグレーションのCIを構成する手間をかけるほどではない場合は便利
php artisan migrate --force

/usr/bin/supervisord -c /etc/supervisord.conf